/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/icons/add.vue')['default']
    Clear: typeof import('./src/components/icons/clear.vue')['default']
    Close: typeof import('./src/components/icons/close.vue')['default']
    Delete: typeof import('./src/components/icons/delete.vue')['default']
    Input: typeof import('./src/components/inputx/input.vue')['default']
    Item: typeof import('./src/components/list/item.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    Modal: typeof import('./src/components/modal/index.vue')['default']
    Moon: typeof import('./src/components/icons/moon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/inputx/select.vue')['default']
    Setting: typeof import('./src/components/icons/setting.vue')['default']
    Slider: typeof import('./src/components/inputx/slider.vue')['default']
    Sun: typeof import('./src/components/icons/sun.vue')['default']
    Switch: typeof import('./src/components/inputx/switch.vue')['default']
    Translate: typeof import('./src/components/icons/translate.vue')['default']
  }
}
